In [1]:
import pandas as pd
import numpy as np

path_to_data = '..\\data\\'

df = pd.read_excel(path_to_data + 'TestData.xlsx')
# similarly, pd.read_csv can be used to read a csv file

# Conditionally update a column
pencil_cost = 3.99
df.loc[df.Item == 'Pencil', 'UnitCost'] = pencil_cost

# Update a column based on other column values
df['Total'] = df['UnitCost'] * df['Units']

# Simple mass remove
df_modified = df[df.Region != 'East']

# print out our result
df_modified

    OrderDate   Region       Rep     Item  Units  UnitCost    Total
1  2020-01-23  Central    Kivell   Binder     50     19.99   999.50
2  2020-02-09  Central   Jardine   Pencil     36      3.99   143.64
3  2020-02-26  Central      Gill      Pen     27     19.99   539.73
4  2020-03-15     West   Sorvino   Pencil     56      3.99   223.44
6  2020-04-18  Central   Andrews   Pencil     75      3.99   299.25
7  2020-05-05  Central   Jardine   Pencil     90      3.99   359.10
8  2020-05-22     West  Thompson   Pencil     32      3.99   127.68
10 2020-06-25  Central    Morgan   Pencil     90      3.99   359.10
14 2020-09-01  Central     Smith     Desk      2    125.00   250.00
16 2020-10-05  Central    Morgan   Binder     28      8.99   251.72
19 2020-11-25  Central    Kivell  Pen Set     96      4.99   479.04
20 2020-12-12  Central     Smith   Pencil     67      3.99   267.33
22 2021-01-15  Central      Gill   Binder     46      8.99   413.54
23 2021-02-01  Central     Smith   Binder     87     15.00  1305.00
25 2021-03-07     West   Sorvino   Binder      7     19.99   139.93
26 2021-03-24  Central   Jardine  Pen Set     50      4.99   249.50
27 2021-04-10  Central   Andrews   Pencil     66      3.99   263.34
29 2021-05-14  Central      Gill   Pencil     53      3.99   211.47
30 2021-05-31  Central      Gill   Binder     80      8.99   719.20
31 2021-06-17  Central    Kivell     Desk      5    125.00   625.00
33 2021-07-21  Central    Morgan  Pen Set     55     12.49   686.95
34 2021-08-07  Central    Kivell  Pen Set     42     23.95  1005.90
35 2021-08-24     West   Sorvino     Desk      3    275.00   825.00
36 2021-09-10  Central      Gill   Pencil      7      3.99    27.93
37 2021-09-27     West   Sorvino      Pen     76      1.99   151.24
38 2021-10-14     West  Thompson   Binder     57     19.99  1139.43
39 2021-10-31  Central   Andrews   Pencil     14      3.99    55.86
40 2021-11-17  Central   Jardine   Binder     11      4.99    54.89
41 2021-12-04  Central   Jardine   Binder     94     19.99  1879.06
42 2021-12-21  Central   Andrews   Binder     28      4.99   139.72

In [2]:
# What about data that has bad values?
df2 = pd.read_excel(path_to_data + 'TestData2.xlsx')

# View first few values of our data
print(df2['OrderDate'].head())
print(df2['OrderDate'].head().isnull())

0                    NaN
1                    NaN
2    2020-02-09 00:00:00
3                    BAD
4    2020-03-15 00:00:00
Name: OrderDate, dtype: object
0     True
1     True
2    False
3    False
4    False
Name: OrderDate, dtype: bool

In [3]:
# We found that "BAD" is a possible value for a null value, so we can read the spreadsheet with that in mind
df2_na_expanded = pd.read_excel(path_to_data + 'TestData2.xlsx', na_values=['BAD'])
print(df2_na_expanded['OrderDate'].head())
print(df2_na_expanded['OrderDate'].head().isnull())

0          NaT
1          NaT
2   2020-02-09
3          NaT
4   2020-03-15
Name: OrderDate, dtype: datetime64[ns]
0     True
1     True
2    False
3     True
4    False
Name: OrderDate, dtype: bool

In [4]:
# Number of units sold is in a bad state, but can't fully be solved like before
print(df2['Units'].head())
print(df2['Units'].head().isnull())

0    Taco
1      50
2     NaN
3    1SD3
4     -20
Name: Units, dtype: object
0    False
1    False
2     True
3    False
4    False
Name: Units, dtype: bool

In [5]:
count=0
df2_cleaned = df2.copy()
for row in df2_cleaned['Units']:
    try:
        # If we can convert to an int, then this is a number 
        int(row)

        # We also want this number to be greater than 0, as a value of 0 or less makes no sense here
        if row <= 0:
            raise ValueError

        pass
    except ValueError:
        # Our value is invalid, so lets set it to NaN
        df2_cleaned.loc[count, 'Units']=np.nan
    count+=1

print(df2_cleaned['Units'].head())
print(df2_cleaned['Units'].head().isnull())

0    NaN
1     50
2    NaN
3    NaN
4    NaN
Name: Units, dtype: object
0     True
1    False
2     True
3     True
4     True
Name: Units, dtype: bool

In [6]:
import time

# Let's look at ways to go about altering a dataframe quickly
df_expanded = pd.read_excel(path_to_data + 'TestData3.xlsx')

# A function that resembles a slow function with complex math
def slow_function(units, cost):
    calculated_total = []
    for count in range(50):
        # do some random math to take a bit of time
        a = np.sqrt((units ** 2  + units ** 2) / 2)
        b = map(np.deg2rad, [units, cost])
        c = np.arcsinh(a)
        calculated_total = units * cost
    return calculated_total

In [7]:

# a C-style loop through everything
df_altered = df_expanded.copy()

time_start = time.perf_counter()
calculated_total = []
for i in range(0, len(df_altered)):
   total = slow_function(df_altered.iloc[i]['Units'], df_altered.iloc[i]['UnitCost'])
   calculated_total.append(total)
df_altered['Total'] = calculated_total
time_stop = time.perf_counter()
print(f"Time taken for C-Style looping: {time_stop - time_start:0.4f} seconds")

Time taken for C-Style looping: 1.0830 seconds

In [8]:
# Using a lambda function
df_altered = df_expanded.copy()

time_start = time.perf_counter()
df_altered['Total'] = df_altered.apply(lambda row: slow_function(row['Units'], row['UnitCost']), axis=1)

time_stop = time.perf_counter()
print(f"Time taken for using a lambda with apply(): {time_stop - time_start:0.4f} seconds")

Time taken for using a lambda with apply(): 0.2934 seconds

In [9]:
# Using pandas vectorization
df_altered = df_expanded.copy()

time_start = time.perf_counter()
df_altered['Total'] = slow_function(df_altered['Units'], df_altered['UnitCost'])

time_stop = time.perf_counter()
print(f"Time taken for using pandas vectorization: {time_stop - time_start:0.4f} seconds")

Time taken for using pandas vectorization: 0.0740 seconds

In [10]:
# Using numpy vectorization
df_altered = df_expanded.copy()

time_start = time.perf_counter()
df_altered['Total'] = slow_function(df_altered['Units'].values, df_altered['UnitCost'].values)

time_stop = time.perf_counter()
print(f"Time taken for using a numpy vectorization: {time_stop - time_start:0.4f} seconds")

Time taken for using a numpy vectorization: 0.0039 seconds